# Generated by Django 3.1.3 on 2021-03-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(default='', max_length=200)),
                ('Admin_contact', models.CharField(default='', max_length=200)),
                ('Admin_email', models.EmailField(default='', max_length=200)),
                ('Admin_password', models.EmailField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=200)),
                ('c_contact', models.CharField(default='', max_length=200)),
                ('c_address', models.TextField(default='')),
                ('c_email', models.EmailField(default='', max_length=200)),
                ('c_country', models.CharField(default='', max_length=100)),
                ('c_state', models.CharField(default='', max_length=100)),
                ('c_city', models.CharField(default='', max_length=100)),
                ('c_pincode', models.CharField(default='', max_length=100)),
                ('c_dob', models.DateField(blank=True, null=True)),
                ('c_password', models.EmailField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(default='', max_length=200)),
                ('d_gender', models.CharField(default='', max_length=200)),
                ('d_email', models.EmailField(default='', max_length=200)),
                ('d_dob', models.DateField(blank=True, null=True)),
                ('d_contact', models.CharField(default='', max_length=200)),
                ('d_address', models.TextField(default='')),
                ('d_aadharno', models.CharField(default='', max_length=100)),
                ('d_shopName', models.CharField(default='', max_length=200)),
                ('d_shopEmail', models.EmailField(default='', max_length=200)),
                ('d_shopAddress', models.TextField(default='')),
                ('d_shopContact', models.CharField(default='', max_length=200)),
                ('d_country', models.CharField(default='', max_length=100)),
                ('d_state', models.CharField(default='', max_length=100)),
                ('d_city', models.CharField(default='', max_length=100)),
                ('d_pincode', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_name', models.CharField(default='', max_length=200)),
                ('j_type', models.CharField(default='', max_length=200)),
                ('j_code', models.CharField(default='', max_length=200)),
                ('j_description', models.TextField(default='')),
                ('j_price', models.CharField(default='', max_length=200)),
                ('j_picture', models.ImageField(default='', max_length=300, upload_to='Images/')),
                ('Dealers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dealer_registration')),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.category_info')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jewellery_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jewellery_info')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(default='', max_length=200)),
                ('pay_cardNo', models.CharField(default='', max_length=200)),
                ('pay_amount', models.CharField(default='', max_length=200)),
                ('pay_totalAmount', models.CharField(default='', max_length=200)),
                ('Customer_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer_info')),
                ('Dealers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dealer_registration')),
                ('Jewellery_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jewellery_info')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('netPrice', models.CharField(default='', max_length=200)),
                ('date_Time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('shippingDetails', models.CharField(default='', max_length=200)),
                ('order_No', models.CharField(default='', max_length=200)),
                ('Customer_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer_info')),
                ('Jewellery_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jewellery_info')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer_info')),
                ('Dealers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dealer_registration')),
                ('Jewellery_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jewellery_info')),
                ('Payment_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_info')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(default='')),
                ('Customer_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer_info')),
                ('Jewellery_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jewellery_info')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jewellery_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jewellery_info')),
            ],
        ),
    ]
